{% set version = "8.1.4" %}

package:
  name: pylama
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pylama/pylama-{{ version }}.tar.gz
  sha256: b920198cd3d22b7a3f288eca3e937258670561139cbb3400d29c28060bc489d0

build:
  number: 0
  noarch: python
  entry_points:
    - pylama = pylama.main:shell
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - mccabe >=0.5.2
    - pycodestyle >=2.3.1
    - pydocstyle >=2.0.0
    - pyflakes >=1.5.0

test:
  imports:
    - pylama
    - pylama.libs
    - pylama.lint

  commands:
    - pylama --help

about:
  home: https://github.com/klen/pylama
  license_file: LICENSE
  license: LGPL 3.0
  license_family: LGPL
  summary: Code audit tool for Python and JavaScript
  dev_url: https://github.com/klen/pylama
  doc_url: https://pylama.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
